if(WIN32)
    set(CMAKE_SYSTEM_NAME Generic)
    set(CMAKE_C_COMPILER "$ENV{DEVKITPRO_PATH}/devkitARM/bin/arm-none-eabi-gcc.exe")
    set(CMAKE_CXX_COMPILER "$ENV{DEVKITPRO_PATH}/devkitARM/bin/arm-none-eabi-g++.exe")
    set(CMAKE_ASM_COMPILER "$ENV{DEVKITPRO_PATH}/devkitARM/bin/arm-none-eabi-as.exe")
    set(CMAKE_AR "$ENV{DEVKITPRO_PATH}/devkitARM/bin/arm-none-eabi-ar.exe")
    set(CMAKE_LD "$ENV{DEVKITPRO_PATH}/devkitARM/bin/arm-none-eabi-ld.exe")
    set(CMAKE_OBJCOPY "$ENV{DEVKITPRO_PATH}/devkitARM/bin/arm-none-eabi-objcopy.exe")
    set(CMAKE_OBJDUMP "$ENV{DEVKITPRO_PATH}/devkitARM/bin/arm-none-eabi-objdump.exe")
    set(CMAKE_SIZE "$ENV{DEVKITPRO_PATH}/devkitARM/bin/arm-none-eabi-size.exe")
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    set(CMAKE_C_FLAGS "-mcpu=arm7tdmi -mtune=arm7tdmi")
    set(CMAKE_CXX_FLAGS "-mcpu=arm7tdmi -mtune=arm7tdmi")
    set(CMAKE_EXE_LINKER_FLAGS "-specs=ds_arm7.specs")
    include_directories("${DEVKITPRO_PATH}/arm-none-eabi/include")
    link_directories("${DEVKITPRO_PATH}/arm-none-eabi/lib")
endif()