#ifndef TEXT
#define TEXT

static const char* text_main_menu[] = {
    "START",
    "SETTINGS",
    "CREDITS"
};

static const char* text_settings[] = {
    "SETTINGS",
    "FRAMERATE:",
    "VIDEO MODE:",
    "ASPECT RATIO:",
    "SENSITIVITY:",
    "BACK",
};

static const char* text_pause_menu[] = {
    "PAUSED",
    "CONTINUE",
    "SETTINGS",
    "EXIT GAME",
};

static const char* text_credits[] = {
    "PlayStation 1 port",
    "Lily Haverlag",
    "",
    "",
    "--Original PC Team--",
    "",
    "",
    "Producer",
    "Tim van der Leeden",
    "",
    "",
    "Product Owner &",
    "Gameplay Programmer",
    "Ralph Warrand",
    "",
    "",
    "Gameplay Programmer",
    "Guy van der Meulen",
    "",
    "",
    "Engine & ",
    "Tools Programmers",
    "Wessel Frijters",
    "Stefan Claasse",
    "Sam van der Hoeven",
    "Joey Staps",
    "",
    "",
    "CICD & Graphics",
    "Programmer",
    "Melvin Rother",
    "",
    "",
    "Sound Designers &",
    "Graphics Programmers",
    "Daniel Cornelisse",
    "Lily Haverlag",
    "",
    "",
    "Narrative, System,",
    "and Level Designer",
    "Attila Szucs",
    "",
    "",
    "Level Designer",
    "Stefanos Zarakovitis",
    "Victor Stanciu",
    "",
    "",
    "Visual Artist",
    "Sasja Bradic",
    "Jesse Reichel",
    "",
    "",
    "Asset Credits",
    "Makkon3 Textures",
    "Ben Makkon Hale",
    "",
    "",
    "Special Thanks",
    "to Ex-devs",
    "Bart van Dongen",
    "Jonathan van der Heide",
    "Silvijn de Vries",
    "Cass van den Bos",
    "Saskia Janssen",
    "",
    "",
    "Special Thanks to Lecturers",
    "",
    "Nick Dry",
    "Bojan Endrovski",
    "David Rhodes",
    "Nicole de Jong",
};

#endif